#!/bin/bash

#
# 1. library name
# 2. source type 1/2/3
#
get_library_source() {
  case $1 in
  config)
    SOURCE_REPO_URL="https://github.com/arthenica/gnu-config"
    SOURCE_ID="805517123cbfe33d17c989a18e78c5789fab0437"
    SOURCE_TYPE="COMMIT"
    ;;
  chromaprint)
    SOURCE_REPO_URL="https://github.com/arthenica/chromaprint"
    SOURCE_ID="v1.6.0"
    SOURCE_TYPE="TAG"
    ;;
  cpu-features)
    SOURCE_REPO_URL="https://github.com/arthenica/cpu_features"
    SOURCE_ID="v0.11.0"
    SOURCE_TYPE="TAG"
    ;;
  dav1d)
    SOURCE_REPO_URL="https://github.com/arthenica/dav1d"
    SOURCE_ID="1.5.3"
    SOURCE_TYPE="TAG"
    ;;
  expat)
    SOURCE_REPO_URL="https://github.com/arthenica/libexpat"
    SOURCE_ID="R_2_8_1"
    SOURCE_TYPE="TAG"
    ;;
  ffmpeg)
    SOURCE_REPO_URL="https://github.com/arthenica/FFmpeg"
    SOURCE_ID="38b88335f99e76ed89ff3c93f877fdefce736c13"
    SOURCE_TYPE="COMMIT"
    ;;
  fontconfig)
    SOURCE_REPO_URL="https://github.com/arthenica/fontconfig"
    SOURCE_ID="2.18.1"
    SOURCE_TYPE="TAG"
    ;;
  freetype)
    SOURCE_REPO_URL="https://github.com/arthenica/freetype2"
    SOURCE_ID="VER-2-14-3"
    SOURCE_TYPE="TAG"
    ;;
  fribidi)
    SOURCE_REPO_URL="https://github.com/arthenica/fribidi"
    SOURCE_ID="v1.0.16"
    SOURCE_TYPE="TAG"
    ;;
  giflib)
    SOURCE_REPO_URL="https://github.com/arthenica/giflib"
    SOURCE_ID="5.2.2"
    SOURCE_TYPE="TAG"
    ;;
  gmp)
    SOURCE_REPO_URL="https://github.com/arthenica/gmp"
    SOURCE_ID="v6.3.0"
    SOURCE_TYPE="TAG"
    ;;
  gnutls)
    SOURCE_REPO_URL="https://github.com/arthenica/gnutls"
    SOURCE_ID="3.7.11"
    SOURCE_TYPE="TAG"
    ;;
  harfbuzz)
    SOURCE_REPO_URL="https://github.com/arthenica/harfbuzz"
    SOURCE_ID="14.2.1"
    SOURCE_TYPE="TAG"
    ;;
  jpeg)
    SOURCE_REPO_URL="https://github.com/arthenica/libjpeg-turbo"
    SOURCE_ID="3.1.4.1"
    SOURCE_TYPE="TAG"
    ;;
  kvazaar)
    SOURCE_REPO_URL="https://github.com/arthenica/kvazaar"
    SOURCE_ID="v2.3.2"
    SOURCE_TYPE="TAG"
    ;;
  lame)
    SOURCE_REPO_URL="https://github.com/arthenica/lame"
    SOURCE_ID="b8f6b9e0fdbfb6fecfc106e8d24af240eac44b22"
    SOURCE_TYPE="COMMIT"
    ;;
  leptonica)
    SOURCE_REPO_URL="https://github.com/arthenica/leptonica"
    SOURCE_ID="1.87.0"
    SOURCE_TYPE="TAG"
    ;;
  libaom)
    SOURCE_REPO_URL="https://github.com/arthenica/libaom"
    SOURCE_ID="v3.12.1"
    SOURCE_TYPE="TAG"
    ;;
  libsvtav1)
    SOURCE_REPO_URL="https://github.com/arthenica/svt-av1"
    SOURCE_ID="v4.1.0"
    SOURCE_TYPE="TAG"
    ;;
  libass)
    SOURCE_REPO_URL="https://github.com/arthenica/libass"
    SOURCE_ID="0.17.4"
    SOURCE_TYPE="TAG"
    ;;
  libiconv)
    SOURCE_REPO_URL="https://github.com/arthenica/libiconv"
    SOURCE_ID="v1.17"
    SOURCE_TYPE="TAG"
    ;;
  libilbc)
    SOURCE_REPO_URL="https://github.com/arthenica/libilbc"
    SOURCE_ID="cd064edf2c6c104a4e1fd87b34fd24cfa6dbe401"
    SOURCE_TYPE="COMMIT"
    ;;
  libjxl)
    SOURCE_REPO_URL="https://github.com/arthenica/libjxl"
    SOURCE_ID="v0.11.2"
    SOURCE_TYPE="TAG"
    ;;
  liblc3)
    SOURCE_REPO_URL="https://github.com/arthenica/liblc3"
    SOURCE_ID="v1.1.3"
    SOURCE_TYPE="TAG"
    ;;
  libogg)
    SOURCE_REPO_URL="https://github.com/arthenica/ogg"
    SOURCE_ID="be05b13e98b048f0b5a0f5fa8ce514d56db5f822"
    SOURCE_TYPE="COMMIT"
    ;;
  libpng)
    SOURCE_REPO_URL="https://github.com/arthenica/libpng"
    SOURCE_ID="v1.6.58"
    SOURCE_TYPE="TAG"
    ;;
  libsamplerate)
    SOURCE_REPO_URL="https://github.com/arthenica/libsamplerate"
    SOURCE_ID="0.2.2"
    SOURCE_TYPE="TAG"
    ;;
  libsndfile)
    SOURCE_REPO_URL="https://github.com/arthenica/libsndfile"
    SOURCE_ID="72f6af15e8f85157bd622ed45b979025828b7001"
    SOURCE_TYPE="COMMIT"
    ;;
  libtheora)
    SOURCE_REPO_URL="https://github.com/arthenica/theora"
    SOURCE_ID="v1.1.1"
    SOURCE_TYPE="TAG"
    ;;
  libuuid)
    SOURCE_REPO_URL="https://github.com/arthenica/libuuid"
    SOURCE_ID="libuuid-1.0.3"
    SOURCE_TYPE="TAG"
    ;;
  libvidstab)
    SOURCE_REPO_URL="https://github.com/arthenica/vid.stab"
    SOURCE_ID="v1.1.1"
    SOURCE_TYPE="TAG"
    ;;
  libvorbis)
    SOURCE_REPO_URL="https://github.com/arthenica/vorbis"
    SOURCE_ID="0657aee69dec8508a0011f47f3b69d7538e9d262"
    SOURCE_TYPE="COMMIT"
    ;;
  libvpx)
    SOURCE_REPO_URL="https://github.com/arthenica/libvpx"
    SOURCE_ID="v1.16.0"
    SOURCE_TYPE="TAG"
    ;;
  libwebp)
    SOURCE_REPO_URL="https://github.com/arthenica/libwebp"
    SOURCE_ID="v1.6.0"
    SOURCE_TYPE="TAG"
    ;;
  libxml2)
    SOURCE_REPO_URL="https://github.com/arthenica/libxml2"
    SOURCE_ID="v2.11.4"
    SOURCE_TYPE="TAG"
    ;;
  nettle)
    SOURCE_REPO_URL="https://github.com/arthenica/nettle"
    SOURCE_ID="nettle_3.8.1_release_20220727"
    SOURCE_TYPE="TAG"
    ;;
  opencore-amr)
    SOURCE_REPO_URL="https://github.com/arthenica/opencore-amr"
    SOURCE_ID="7dba8c32238418ce0b316a852b2224df586ca896"
    SOURCE_TYPE="COMMIT"
    ;;
  openh264)
    SOURCE_REPO_URL="https://github.com/arthenica/openh264"
    SOURCE_ID="v2.3.1"
    SOURCE_TYPE="TAG"
    ;;
  openssl)
    SOURCE_REPO_URL="https://github.com/arthenica/openssl"
    SOURCE_ID="openssl-3.5.7"
    SOURCE_TYPE="TAG"
    ;;
  opus)
    SOURCE_REPO_URL="https://github.com/arthenica/opus"
    SOURCE_ID="ddbe48383984d56acd9e1ab6a090c54ca6b735a6"
    SOURCE_TYPE="COMMIT"
    ;;
  rapidjson)
    SOURCE_REPO_URL="https://github.com/arthenica/rapidjson"
    SOURCE_ID="24b5e7a8b27f42fa16b96fc70aade9106cf7102f"
    SOURCE_TYPE="COMMIT"
    ;;
  rubberband)
    SOURCE_REPO_URL="https://github.com/arthenica/rubberband"
    SOURCE_ID="v4.0.0"
    SOURCE_TYPE="TAG"
    ;;
  sdl)
    SOURCE_REPO_URL="https://github.com/arthenica/SDL"
    SOURCE_ID="release-2.32.10"
    SOURCE_TYPE="TAG"
    ;;
  shine)
    SOURCE_REPO_URL="https://github.com/arthenica/shine"
    SOURCE_ID="97f188efc3dc90315b79a2af1f477c0c18d85e82"
    SOURCE_TYPE="COMMIT"
    ;;
  snappy)
    SOURCE_REPO_URL="https://github.com/arthenica/snappy"
    SOURCE_ID="1.2.2"
    SOURCE_TYPE="TAG"
    ;;
  soxr)
    SOURCE_REPO_URL="https://github.com/arthenica/soxr"
    SOURCE_ID="945b592b70470e29f917f4de89b4281fbbd540c0"
    SOURCE_TYPE="COMMIT"
    ;;
  speex)
    SOURCE_REPO_URL="https://github.com/arthenica/speex"
    SOURCE_ID="5dceaaf3e23ee7fd17c80cb5f02a838fd6c18e01"
    SOURCE_TYPE="COMMIT"
    ;;
  srt)
    SOURCE_REPO_URL="https://github.com/arthenica/srt"
    SOURCE_ID="v1.5.5"
    SOURCE_TYPE="TAG"
    ;;
  tesseract)
    SOURCE_REPO_URL="https://github.com/arthenica/tesseract"
    SOURCE_ID="5.4.1"
    SOURCE_TYPE="TAG"
    ;;
  tiff)
    SOURCE_REPO_URL="https://github.com/arthenica/libtiff"
    SOURCE_ID="v4.7.1"
    SOURCE_TYPE="TAG"
    ;;
  twolame)
    SOURCE_REPO_URL="https://github.com/arthenica/twolame"
    SOURCE_ID="bec4069996479aa1aa9d9e7fa32c33135b3a2047"
    SOURCE_TYPE="COMMIT"
    ;;
  vo-amrwbenc)
    SOURCE_REPO_URL="https://github.com/arthenica/vo-amrwbenc"
    SOURCE_ID="080af7540562e4adfbd3312837fe5fc6771c4cd0"
    SOURCE_TYPE="COMMIT"
    ;;
  vvenc)
    SOURCE_REPO_URL="https://github.com/arthenica/vvenc"
    SOURCE_ID="v1.14.0"
    SOURCE_TYPE="TAG"
    ;;
  x264)
    SOURCE_REPO_URL="https://github.com/arthenica/x264"
    SOURCE_ID="b35605ace3ddf7c1a5d67a2eb553f034aef41d55"
    SOURCE_TYPE="COMMIT"
    ;;
  x265)
    SOURCE_REPO_URL="https://github.com/arthenica/x265"
    SOURCE_ID="4.2"
    SOURCE_TYPE="TAG"
    ;;
  xvidcore)
    SOURCE_REPO_URL="https://github.com/arthenica/xvidcore"
    SOURCE_ID="release-1_3_7"
    SOURCE_TYPE="TAG"
    ;;
  zimg)
    SOURCE_REPO_URL="https://github.com/arthenica/zimg"
    SOURCE_ID="release-3.0.6"
    SOURCE_TYPE="TAG"
    ;;
  esac

  case $2 in
  1)
    echo "${SOURCE_REPO_URL}"
    ;;
  2)
    CUSTOM_VERSION_FLAG=$(echo "version_$1" | sed "s/\-/\_/g")
    if [[ ! -z "${!CUSTOM_VERSION_FLAG}" ]]; then
      echo "${!CUSTOM_VERSION_FLAG}"
    else
      echo "${SOURCE_ID}"
    fi
    ;;
  3)
    echo "${SOURCE_TYPE}"
    ;;
  esac
}
